version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - cd bia
      - sam build
      - sam package --output-template-file ../template-out-bia-serverless.yaml --s3-bucket bia-pipeline-us-east-1-lsa --s3-prefix bia-serverless

artifacts:
  files:
    - template-out-bia-serverless.yaml
