version = 0.1

[default.local_start_api.parameters]
docker_network = "bia_serveless"
env_vars = "env.json"

[default.deploy.parameters]
stack_name = "bia-serverless"
resolve_s3 = true
s3_prefix = "bia-serverless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
