AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bia-serverless

  Sample SAM Template for bia-serverless
Parameters:
  SecurityGroup:
    Type: String
    Description: ID do security group
  DBName:
    Type: String
    Description: Nome da base de dados
  DBSecretArn:
    Type: String
    Description: ARN do secret com credenciais do banco
    NoEcho: true
  DBHost:
    Type: String
    Description: Host da base de dados
  DBPort:
    Type: String
    Description: Porta da base de dados
    Default: "5432"

Globals:
  Function:
    Timeout: 3
    MemorySize: 512
    VpcConfig:
      SecurityGroupIds:
      - !Ref SecurityGroup
      SubnetIds:
        - "subnet-0339dd8358d0d396c"
        - "subnet-0f4978239390808f8"
    Environment:
      Variables:
        DB_SECRET_ARN: !Ref DBSecretArn
        DB_HOST: !Ref DBHost
        DB_PORT: !Ref DBPort
  Api:
    Cors:
      AllowMethods: "'GET, PUT, POST, DELETE, OPTIONS'"
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-type, x-api-key'"

Resources:  
  TarefasFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: lambda.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        ApiPing:
          Type: Api 
          Properties:
            Path: /api/ping
            Method: get  
        GetTarefas:
          Type: Api 
          Properties:
            Path: /api/tarefas
            Method: get
        PostTarefa:
          Type: Api 
          Properties:
            Path: /api/tarefas
            Method: post
        GetTarefa:
          Type: Api 
          Properties:
            Path: /api/tarefas/{uuid}
            Method: get
        UpdatePriority:
          Type: Api 
          Properties:
            Path: /api/tarefas/update_priority/{uuid}
            Method: put
        DeleteTarefa:
          Type: Api 
          Properties:
            Path: /api/tarefas/{uuid}
            Method: delete
      Policies:
        - SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TarefasApi:
    Description: "API Gateway endpoint URL for Prod stage for Tarefas function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/tarefas"
  TarefasFunction:
    Description: "Tarefas Lambda Function ARN"
    Value: !GetAtt TarefasFunction.Arn
  TarefasFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TarefasFunctionRole.Arn